package by.grsu.ioda.artifact.controller;

import by.grsu.ioda.artifact.model.Service;
import by.grsu.ioda.artifact.repository.ServiceRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/services")
public class servicesController {

    @Autowired // This means to get the bean called routeRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ServiceRepository serviceRepository;

    @GetMapping
    public String servicesController(Model model) {

        Iterable<Service> serviceObjects = serviceRepository.findAll();
        model.addAttribute("services", serviceObjects);

		for (Service r : serviceObjects) {
			System.out.println(r);
		}

        return "services";
    }
}
